workspace:
  base: /var/www/owncloud
  path: apps/user_management

branches: [master]

pipeline:
  install-server:
    image: owncloudci/core
    pull: true
    GIT_REFERENCE: ${OC_VERSION}
    db_type: mysql
    db_name: owncloud
    db_host: mysql:3306
    db_username: owncloud
    db_password: owncloud
    when:
      matrix:
        NEED_SERVER: true

  owncloud-log:
    image: owncloud/ubuntu:16.04
    detach: true
    pull: true
    commands:
      - tail -f /var/www/owncloud/data/owncloud.log

  install-app:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - cd /var/www/owncloud/apps/user_management
      - make
      - cd /var/www/owncloud/
      - php occ a:l
      - php occ a:e user_management
      - php occ a:e testing
      - php occ a:l
      - php occ config:system:set trusted_domains 1 --value=server
      - php occ config:system:set trusted_domains 2 --value=federated
      - php occ log:manage --level 0
    when:
      matrix:
        NEED_INSTALL_APP: true

  run-acceptance-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - BROWSER=chrome #chrome or firefox
      - SELENIUM_HOST=selenium
      - SRV_HOST_NAME=server
      - SRV_HOST_PORT=80
      - REMOTE_FED_SRV_HOST_NAME=federated
      - REMOTE_FED_SRV_HOST_PORT=80
      - SKELETON_DIR=/var/www/owncloud/tests/ui/skeleton
      - SELENIUM_PORT=4444
      - PLATFORM=Linux
      - TEST_EXTERNAL_USER_BACKENDS=true
    commands:
      - cd /var/www/owncloud
      - chown www-data * -R
      - chmod +x lib/composer/behat/behat/bin/behat
      - rm lib/composer/bin/behat
      - ln -s ../behat/behat/bin/behat lib/composer/bin/behat
      - chmod 777 /var/www/owncloud/tests/ui/filesForUpload -R
      - bash tests/travis/start_ui_tests.sh --remote --tags '@TestAlsoOnExternalUserBackend&&~@skipOnLDAP'
    when:
      matrix:
        TEST_SUITE: acceptance

  lint-test:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - cd /var/www/owncloud/apps/user_management
      - make
      - vendor/bin/parallel-lint  --exclude vendor .
    when:
      matrix:
        TEST_SUITE: lint

  phpunit-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - cd /var/www/owncloud
      - chmod +x lib/composer/phpunit/phpunit/phpunit
      - rm lib/composer/bin/phpunit
      - ln -s ../phpunit/phpunit/phpunit lib/composer/bin/phpunit
      - phpdbg -d memory_limit=4096M -rr ./lib/composer/bin/phpunit --configuration apps/user_management/tests/unit/phpunit.xml
    when:
      matrix:
        TEST_SUITE: phpunit

  js-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - make test-js
    when:
      matrix:
        TEST_SUITE: javascript

  codecov:
    image: robertstettner/drone-codecov
    pull: true
    files:
      - apps/user_management/tests/unit/clover.xml
    token: af884a52-14ff-4e5c-91f9-ce4f79469623
    when:
      matrix:
        TEST_SUITE: phpunit
        PHP_VERSION: 7.1

services:
  server:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - APACHE_WEBROOT=/var/www/owncloud/
    command: [ "/usr/local/bin/apachectl", "-e", "debug" , "-D" , "FOREGROUND" ]
    when:
      matrix:
        TEST_SUITE: acceptance

  federated:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - APACHE_WEBROOT=/var/www/owncloud/
    command: [ "/usr/local/bin/apachectl", "-e", "debug" , "-D" , "FOREGROUND" ]
    when:
      matrix:
        TEST_SUITE: acceptance

  selenium:
    image: selenium/standalone-chrome-debug:latest
    pull: true
    when:
      matrix:
        TEST_SUITE: acceptance

  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=owncloud
      - MYSQL_ROOT_PASSWORD=owncloud
    when:
      matrix:
        TEST_SUITE: [ phpunit, javascript ]

matrix:
  include:
   - TEST_SUITE: javascript
     PHP_VERSION: 7.1
     OC_VERSION: master
     NEED_SERVER: true
     NEED_INSTALL_APP: true

#syntax lint check
   - TEST_SUITE: lint
     PHP_VERSION: 7.1
     NEED_SERVER: false
     NEED_INSTALL_APP: false
   - TEST_SUITE: lint
     PHP_VERSION: 5.6
     NEED_SERVER: false
     NEED_INSTALL_APP: false
     
#unit tests
   - TEST_SUITE: phpunit
     PHP_VERSION: 7.1
     OC_VERSION: master
     NEED_SERVER: true
     NEED_INSTALL_APP: true
     
   - TEST_SUITE: phpunit
     PHP_VERSION: 7.2
     OC_VERSION: master
     NEED_SERVER: true
     NEED_INSTALL_APP: true

   - TEST_SUITE: phpunit
     PHP_VERSION: 5.6
     OC_VERSION: stable10
     NEED_SERVER: true
     NEED_INSTALL_APP: true

#acceptance tests
#   - TEST_SUITE: acceptance
#     OC_VERSION: daily-master-qa
#     PHP_VERSION: 7.1
#     NEED_SERVER: true
#     NEED_INSTALL_APP: true
#
#   - TEST_SUITE: acceptance
#     OC_VERSION: daily-stable10-qa
#     PHP_VERSION: 5.6
#     NEED_SERVER: true
#     NEED_INSTALL_APP: true
#
#   - TEST_SUITE: acceptance
#     OC_VERSION: daily-stable10-qa
#     PHP_VERSION: 7.0
#     NEED_SERVER: true
#     NEED_INSTALL_APP: true
