workspace:
  base: /var/www/owncloud
  path: apps/user_management

branches: [ master, release* ]

pipeline:
  install-server:
    image: owncloudci/core
    pull: true
    version: ${OC_VERSION}
    db_type: mysql
    db_name: owncloud
    db_host: mysql:3306
    db_username: owncloud
    db_password: owncloud
    when:
      matrix:
        NEED_SERVER: true

  install-testrunner:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - git clone -b master --depth=1 https://github.com/owncloud/core.git /var/www/owncloud/testrunner
      - cd /var/www/owncloud/testrunner
      - make install-composer-deps
      - make vendor-bin-deps
    when:
      matrix:
        NEED_TARBALL: true

  install-app:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - cd /var/www/owncloud/
      - php occ a:l
      - php occ a:e user_management
      - php occ a:e testing
      - php occ a:l
      - php occ config:system:set trusted_domains 1 --value=server
      - php occ config:system:set trusted_domains 2 --value=federated
      - php occ log:manage --level 2
      - php occ config:system:set --value true --type boolean integrity.check.disabled
    when:
      matrix:
        NEED_INSTALL_APP: true

  fix-permissions:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - chown www-data /var/www/owncloud -R
      - if [ "${NEED_TARBALL}" = "true" ];
        then chmod 777 /var/www/owncloud/testrunner/tests/acceptance/filesForUpload -R;
        chmod +x /var/www/owncloud/testrunner/tests/acceptance/run.sh;
        else chmod 777 /var/www/owncloud/tests/acceptance/filesForUpload -R;
        chmod +x /var/www/owncloud/tests/acceptance/run.sh; fi
    when:
      matrix:
        NEED_SERVER: true

  owncloud-log:
    image: owncloud/ubuntu:16.04
    detach: true
    pull: true
    commands:
      - tail -f /var/www/owncloud/data/owncloud.log
    when:
      matrix:
        NEED_SERVER: true

  owncloud-coding-standard:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - make test-php-style
    when:
      matrix:
        TEST_SUITE: owncloud-coding-standard

  phpunit-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - PHP_VERSION=${PHP_VERSION}
      - COVERAGE=${COVERAGE}
    commands:
      - if [ -z "${COVERAGE}" ]; then make test-php-unit; fi
      - if [ "${COVERAGE}" = "true" ]; then make test-php-unit-dbg; fi
    when:
      matrix:
        TEST_SUITE: phpunit

  webui-acceptance-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - BROWSER=chrome #chrome or firefox
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
      - TEST_SERVER_URL=http://server
      - TEST_SERVER_FED_URL=http://federated
      - PLATFORM=Linux
      - BEHAT_SUITE=${BEHAT_SUITE}
      - MAILHOG_HOST=email
    commands:
      - if [ "${NEED_TARBALL}" = "true" ]; then cd /var/www/owncloud/testrunner; fi
      - make test-acceptance-webui
    when:
      matrix:
        TEST_SUITE: web-acceptance

  js-tests:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    commands:
      - make test-js
    when:
      matrix:
        TEST_SUITE: javascript

  codecov:
    image: plugins/codecov:2
    secrets: [codecov_token]
    pull: true
    paths:
      - tests/output/clover.xml
    files:
      - '*.xml'
    when:
      matrix:
        COVERAGE: true

  notify:
    image: plugins/slack:1
    pull: true
    secrets: [ slack_webhook ]
    channel: builds
    when:
      status: [ failure, changed ]
      event: [ push, tag ]

services:
  server:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - APACHE_WEBROOT=/var/www/owncloud/
    command: [ "/usr/local/bin/apachectl", "-e", "debug", "-D", "FOREGROUND" ]
    when:
      matrix:
        NEED_SERVER: true

  federated:
    image: owncloudci/php:${PHP_VERSION}
    pull: true
    environment:
      - APACHE_WEBROOT=/var/www/owncloud/
    command: [ "/usr/local/bin/apachectl", "-e", "debug", "-D", "FOREGROUND" ]
    when:
      matrix:
        NEED_SERVER: true

  selenium:
    image: selenium/standalone-chrome-debug:3.141.59-oxygen
    pull: true
    when:
      matrix:
        TEST_SUITE: web-acceptance

  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=owncloud
      - MYSQL_ROOT_PASSWORD=owncloud
    when:
      matrix:
        NEED_SERVER: true

  email:
    image: mailhog/mailhog
    pull: true
    when:
      matrix:
        USE_EMAIL: true

matrix:
  include:
    # owncloud-coding-standard
    - PHP_VERSION: 7.2
      TEST_SUITE: owncloud-coding-standard

    - PHP_VERSION: 7.1
      TEST_SUITE: owncloud-coding-standard

    - TEST_SUITE: javascript
      PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      NEED_SERVER: true
      NEED_INSTALL_APP: true

    #unit tests
    - TEST_SUITE: phpunit
      PHP_VERSION: 7.1
      OC_VERSION: daily-master-qa
      NEED_SERVER: true
      NEED_INSTALL_APP: true
      COVERAGE: true

    - TEST_SUITE: phpunit
      PHP_VERSION: 7.2
      OC_VERSION: daily-master-qa
      NEED_SERVER: true
      NEED_INSTALL_APP: true

    #acceptance tests
    - TEST_SUITE: web-acceptance
      OC_VERSION: daily-master-qa
      PHP_VERSION: 7.1
      NEED_SERVER: true
      NEED_INSTALL_APP: true
      BEHAT_SUITE: webUIAddUsers
      USE_EMAIL: true

    - TEST_SUITE: web-acceptance
      OC_VERSION: daily-master-qa
      PHP_VERSION: 7.1
      NEED_SERVER: true
      NEED_INSTALL_APP: true
      BEHAT_SUITE: webUIManageQuota
      USE_EMAIL: true

    - TEST_SUITE: web-acceptance
      OC_VERSION: daily-master-qa
      PHP_VERSION: 7.1
      NEED_SERVER: true
      NEED_INSTALL_APP: true
      BEHAT_SUITE: webUIManageUsersGroups
      USE_EMAIL: true

    - TEST_SUITE: web-acceptance
      OC_VERSION: daily-master-qa
      PHP_VERSION: 7.1
      NEED_SERVER: true
      NEED_INSTALL_APP: true
      BEHAT_SUITE: webUISettingsMenu
      USE_EMAIL: true

    # Owncloud Tarball
    - TEST_SUITE: web-acceptance
      OC_VERSION: 10.2.1
      PHP_VERSION: 7.1
      NEED_SERVER: true
      NEED_INSTALL_APP: true
      BEHAT_SUITE: webUIAddUsers
      USE_EMAIL: true
      NEED_TARBALL: true

    - TEST_SUITE: web-acceptance
      OC_VERSION: 10.2.1
      PHP_VERSION: 7.1
      NEED_SERVER: true
      NEED_INSTALL_APP: true
      BEHAT_SUITE: webUIManageQuota
      USE_EMAIL: true
      NEED_TARBALL: true

    - TEST_SUITE: web-acceptance
      OC_VERSION: 10.2.1
      PHP_VERSION: 7.1
      NEED_SERVER: true
      NEED_INSTALL_APP: true
      BEHAT_SUITE: webUIManageUsersGroups
      USE_EMAIL: true
      NEED_TARBALL: true

    - TEST_SUITE: web-acceptance
      OC_VERSION: 10.2.1
      PHP_VERSION: 7.1
      NEED_SERVER: true
      NEED_INSTALL_APP: true
      BEHAT_SUITE: webUISettingsMenu
      USE_EMAIL: true
      NEED_TARBALL: true
